### ISSUE TITLE
RFE: Set profile in stack group config

### ISSUE THREAD

**Issue by otto-liljalaakso-nt** [takomo-io/takomo#444]
We currently use Takomo to deploy an application that is split between multiple AWS accounts.
One axis is stage: we have development and production accounts.
Another is functional: we have the main application account, backup account and tooling account.

Currently, AWS credentials to all these accounts are managed by using Takomo's [Command role](https://takomo.io/docs/stack-properties/command-role) configuration:
Each developer's IAM user and the IAM role used by CI are allowed to assume a suitable role in each account,
and each stack group's configuration specifies that role as `commandRole`.
 
Recently, we switched to use AWS IAM Identity Center for developer credentials.
Consequently, developers now use profiles and `aws sso login` for AWS CLI.
We would like to simplify our setup by removing the role switching entirely.
However, it looks like it is not possible to instruct Takomo to switch profiles when deploying each stack group,
similarly to how role switching works with `commandRole`.
 
Would it be possible to add profile switching based on stack group, or is there a different way to switch profiles?

**Comment by hmeltaus** [comment]
Instead of switching profiles which are always defined locally by the developer, I would recommend the following strategy. 

Have one "tooling account" from where developers can assume a "global deployer role" using `aws sso login`. This global deployer role has permissions to assume "account-specific deployer roles" from all of your target accounts. The account-specific roles needs to have trust policy that allows the tooling account and CI to assume the role. Configure account-specific roles to Takomo stack configuration with `commandRole`. 

Now, when a developer needs to perform deployment, they use `aws sso login` to assume the global deployer role from the tooling account and then run the takomo deploy command. Takomo uses the credentials from sso login to assume account-specific deployer roles.

We have used this approach and it works very well. You can use CloudFormation stack sets to deploy account-specific deployer roles to the target accounts automatically whenever a new account is created. I think you already have these account-specific roles in place (the roles you specify with `commandRole`), so you only need to create the tooling account (or nominate some existing account) and the global deployer role.

If needed, you can have more than one global deployer role. Maybe one for development environments and another for production environments. You can assign developers to SSO groups which grant them permissions to assume one or more global deployer roles based on their role in the company.

I hope I was able to explain this well enough =)

**Comment by hmeltaus** [comment]
You interpreted correctly. Feel free to reopen this issue should you have more questions.
